version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.eclipse.jetty:jetty-maven-plugin
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
  - dependency-name: org.n52.arctic-sea:shetland
    versions:
    - 8.1.0
